### ISSUE TITLE
render problem

### ISSUE THREAD

**Issue by Austin13579** [akashsengupta1997/HierarchicalProbabilistic3DHuman#5]
Hello,

When I run the Inference Step,
I got:
Traceback (most recent call last):
  File "run_predict.py", line 126, in <module>
    gender=args.gender)
  File "run_predict.py", line 90, in run_predict
    visualise_samples=visualise_samples)
  File "/Users/mac/Desktop/reconstruction/predict/predict_poseMF_shapeGaussian_net.py", line 197, in predict_poseMF_shapeGaussian_net
    verts_features=vertex_var_colours)
  File "/opt/anaconda3/envs/ll/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/mac/Desktop/reconstruction/renderers/pytorch3d_textured_renderer.py", line 275, in forward
    fragments = self.rasterizer(meshes_iuv, cameras=self.cameras)
  File "/opt/anaconda3/envs/ll/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/ll/lib/python3.6/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 151, in forward
    cull_backfaces=raster_settings.cull_backfaces,
  File "/opt/anaconda3/envs/ll/lib/python3.6/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 150, in rasterize_meshes
    cull_backfaces,
  File "/opt/anaconda3/envs/ll/lib/python3.6/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 205, in forward
    cull_backfaces,
RuntimeError: NOT IMPLEMENTED
"

Do you have any idea on it?

**Comment by akashsengupta1997** [comment]
Hi, this sounds like an error that occurs when you try to render on pytorch3d without a CUDA-enabled GPU - are you running the code on CPU only?

(Technically pytorch3d can work on CPU only, but you may have to modify my code somehow to get it work work)

**Comment by Austin13579** [comment]
Thank you for your kindly response. I ran the code in Mac before, and I will test it on GPU.
